adj1=input("Enter an Adjective: ")
noun1=input("Enter a noun: ")
adj2=input("Enter an Adjective: ")
verb=input("Enter a verb ending with ing: ")
adj3=input("Enter an Adjective: ")

print(f"Today I went to a {adj1} zoo.")
print(f"In an exhibit, I saw a {noun1}.")
print(f"{noun1} was {adj2} and {verb}")
print(f"I was {adj3}!")